package baseconst

const (
	User                        = "User"
	Session                     = "Session"
	UsersSessions               = "UsersSessions"
	OTP                         = "OTP"
	Notification                = "Notification"
	AwsConfig                   = "AwsConfig"
	RBAC                        = "RBAC"
	Roles                       = "Roles"
	Sports                      = "Sports"
	Levels                      = "Levels"
	Settings                    = "Settings"
	Events                      = "Events"
	Pals                        = "Pals"
	UserSports                  = "UserSports"
	Chat                        = "Chat"
	ChatParticipant             = "ChatParticipant"
	ChatMessage                 = "ChatMessage"
	EventInvitation             = "EventInvitation"
	ChatProcessor               = "ChatProcessor"
	Venue                       = "Venue"
	VenueReview                 = "VenueReview"
	Facility                    = "Facility"
	FacilityAvailabilityPattern = "FacilityAvailabilityPattern"
	FacilityBooking             = "FacilityBooking"
	PalsReport                  = "PalsReport"
	PalsReportDetail            = "PalsReportDetail"
	VenueReport                 = "VenueReport"
	VenueReportDetail           = "VenueReportDetail"
	ChatSupportMessage          = "ChatSupportMessage"
	Agent                       = "Agent"
	SuggestLevel                = "SuggestLevel"
)
